Server:
  Mode: debug #debug or release or test
  Addr: "0.0.0.0"
  Port: 8080
  ReadTimeout: 600
  WriteTimeout: 600

Logger:
  OpenLogger: true # 默认开启滚动日志，可以手动关闭
  FilePath: "runtime/logs" # 日志文件路径,必须为绝对路径
  MaxSize: 128 # 每个日志文件保存的最大尺寸 单位：M 默认128
  MaxBackups: 30 # 日志文件最多保存多少个备份 默认30
  MaxAge: 7 # 文件最多保存多少天 默认 7
  Compress: true # 是否压缩 默认true