// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/cuiyuanxin/airuisi-admin/internal/router"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func newApp(logger *zap.Logger) (*gin.Engine, error) {
	engine := router.NewRouter()
	return engine, nil
}

// wire.go:

var ServerSet = wire.NewSet(router.NewRouter)
